version: '3.5'

services:

    service.nginx:
      image: nginx:alpine
      container_name: emby-nginx
      ports:
        - 8095:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/embyCache:/var/cache/nginx/emby
      restart: always
      depends_on:
        - service.ali

    service.ali:
      image: xhofe/alist:v2
      container_name: alist
      ports:
        - 5244:5244
      volumes:
        - ./alist:/opt/alist/data
      restart: always